server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password: 1234

  redis:
    host: "localhost"
    port: 6379

  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: local
      username: root
      password: 1234
