server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password: 1234

  redis:
    host: "localhost"
    port: 6379

  # 어째서인지 properties 파일로 설정해야 연동된다..
#  data:
#    mongodb:
#      authentication-database: admin
#      host: localhost
#      port: 27017
#      database: admin
#      username: root
#      password: 1234