management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  main:
    allow-bean-definition-overriding: true

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:old_batch;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: embedded

---

spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 커넥터 최신 버전은 cj가 들어감
    url: jdbc:mysql://localhost/batch-lecture
    username: root
    password: 1234

  batch:
    jdbc:
      # 메타데이터 테이블 생성 여부
      initialize-schema: always
#      table-prefix:
    job:
      # spring 실행시 job 실행 여부
      enabled: true
      # spring 실행시 동작할 job 이름 지정
      # args 넣어줄수도 있고, 없으면 NONE
#      names: ${job.name:NONE}


